version: '3.7' # composeファイルのバーション指定
services:
  NotifyOfficeIlluminance: # service名
    build: . # ビルドに使用するDockerfileがあるディレクトリ指定
    tty: true # コンテナの起動永続化
    volumes:
      - .:/go/src/github.com/katsuomi/NotifyOfficeIlluminance # マウントディレクトリ指定
    ports:
      - "8080:8080"
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: NotifyOfficeIlluminance
      POSTGRES_PASSWORD: NotifyOfficeIlluminance
      POSTGRES_DB: NotifyOfficeIlluminance
    ports:
      - 5432:5432